name: Windows CI Test

on: [push]

jobs:
  test-on-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Say Hello from Windows
        run: |
          echo "Running on Windows!"
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
